services:
  redis-master:
    image: redis:7.4
    container_name: redis-master
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./master/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - redis-net

  redis-slave1:
    image: redis:7.4
    container_name: redis-slave1
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    depends_on:
      - redis-master
    volumes:
      - ./slave/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-net

  redis-slave2:
    image: redis:7.4
    container_name: redis-slave2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    depends_on:
      - redis-master
    volumes:
      - ./slave/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-net

  sentinel1:
    image: redis:7.4
    container_name: sentinel1
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]
    depends_on:
      - redis-master
    volumes:
      - ./sentinel/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    ports:
      - "26379:26379"
    networks:
      - redis-net

  sentinel2:
    image: redis:7.4
    container_name: sentinel2
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]
    depends_on:
      - redis-master
    volumes:
      - ./sentinel/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    ports:
      - "26380:26379"
    networks:
      - redis-net

  sentinel3:
    image: redis:7.4
    container_name: sentinel3
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]
    depends_on:
      - redis-master
    volumes:
      - ./sentinel/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    ports:
      - "26381:26379"
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
